///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModel {
/*
{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXIiOiJtb3JfMjMxNCIsImlhdCI6MTY4NjM4MDI0NX0.Gvb8ya5-_BBOL6tyzwZizeoNTAlpWCxtB2heLez1oIo"
} 
*/

  String? token;

  LoginModel({
    this.token,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    token = json['token']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['token'] = token;
    return data;
  }
}
